###

Content-Type: application/json



###
http://localhost:3000


/////////////////////////
// Workouts

###
http://localhost:3000/api/v1/workouts

###
POST http://localhost:3000/api/v1/workouts/seed

###
POST http://localhost:3000/api/v1/workouts

Content-Type: application/json

{
  "workout": {
    "name": "Sharms Day",
    "description": "Shoulders, Tris and Bis",
    "userId": 1
  },
  "userId": 1
}

/////////////////////////
// Users

###
POST http://localhost:3000/api/v1/users/seed

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "firstName": "Brandon",
  "lastName": "Koszyk",
  "email": "koszykb1@gmail.com",
  "password": "koszyk"
}

###
PATCH http://localhost:3000/api/v1/users/4
Content-Type: application/json

{
  "firstName": "Brandon Koszyk"
}

###
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
  "firstName": "Brandon",
  "lastName": "Koszyk",
  "email": "koszykb1@gmail.com",
  "password": "koszyk"
}

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "koszykb1@gmail.com",
  "password": "koszyk"
}